2019-03-05 19:03:37,529 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 3076327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 20:36:35,983 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 5538425ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 21:36:28,517 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 3572522ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 21:57:21,031 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212502ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 22:17:52,475 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211431ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 22:38:44,993 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212511ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 22:59:16,379 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211375ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 23:19:49,013 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-05 23:40:40,394 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211361ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 00:01:11,959 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211555ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 00:22:04,471 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212498ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 00:42:36,753 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212268ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 01:03:28,122 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211352ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 01:24:00,636 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212499ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 01:44:33,014 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212370ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 02:05:24,403 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211357ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 02:25:56,961 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212551ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 02:46:48,385 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211407ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 03:07:20,801 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212410ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 03:28:12,240 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211420ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 03:48:44,501 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212247ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 04:09:16,014 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211501ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 04:30:07,557 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211520ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 04:50:39,849 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212283ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 05:06:55,304 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 935442ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 05:22:52,691 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 897362ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 05:32:43,955 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 571253ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 05:53:17,016 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1213047ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 06:14:08,561 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211528ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 06:34:39,966 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211397ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 06:55:31,356 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211382ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 07:16:03,789 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212428ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 07:36:55,219 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 07:57:26,757 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211530ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 08:17:58,158 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211390ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 08:38:50,544 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212379ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 08:59:21,845 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1211291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 09:20:14,236 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 1212383ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 09:25:28,490 ERROR 34392 nodejs.ClusterClientNoResponseError: client no response in 294244ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 34392
hostname: localhost

2019-03-06 16:36:55,347 ERROR 36292 nodejs.ClusterClientNoResponseError: client no response in 996712ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 36292
hostname: localhost

2019-03-07 15:41:50,256 ERROR 39978 nodejs.ClusterClientNoResponseError: client no response in 733869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/lixiao/Desktop/egg-pwa/egg-pwa-new/node_modules/cluster-client/lib/leader.js:74:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
name: "ClusterClientNoResponseError"
pid: 39978
hostname: localhost

